version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=snorlax_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      # persisting postgresql data
      # - ./postgres-data:/var/lib/postgresql/data
      # delete all content under /tmp once run docker-compose up
      - ./postgres-data:/tmp
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    build: ./snorlax/
    command: ["python", "main.py"]
    depends_on:
      - postgres
    volumes:
      - ./snorlax:/code
  test:
    build: ./snorlax/
    command: python -m pytest tests --capture=sys --tb=no --cov=modules
    depends_on:
      - postgres
    volumes:
      - ./snorlax:/code
